### ISSUE TITLE
Open git repository on zwiki.org/zwikidir/.git

### ISSUE THREAD

**Issue by aman566** [simonmichael/ZWiki#4]
The git repository should not be opened other then on github. Hope you will close this or give 403 error when visiting it.

**Comment by simonmichael** [comment]
Thanks for this report, and sorry for the slow response. The /zwikidir filesystem has been removed.

**Comment by aman566** [comment]
Am I eligible for swag/bounty?

Regards
Aman

**Comment by simonmichael** [comment]
If I ever have Zwiki swag, I promise you will be first on the recipient list. :-)

Do you use Zwiki ?

**Comment by aman566** [comment]
Small bounty would be great as the git repository was a critical issue.
Also am I permitted to find more bugs and report it to you directly?

Regards
Aman

**Comment by simonmichael** [comment]
@aman566 I'll offer you a choice: a $25 paypal to your email address, or half an hour of one-on-one coaching/support. Bug reports for any of my projects are appreciated, but there are no bounties on offer at the moment. Except for [these](https://github.com/simonmichael/hledger/issues?utf8=%E2%9C%93&q=+is%3Aissue+is%3Aopen+label%3Abounty+) and [this](https://github.com/jtdaugherty/vty/pull/1#issuecomment-297144653).

**Comment by aman566** [comment]
$25 will be appreciated as I will use it to buy pentesting labs.
Paypal id: npgupta1969@gmail.com

Regards
Aman

**Comment by aman566** [comment]
Sir you should send $26.40 as paypal will deduct $1.40 as transaction fee.

Regards
Aman

**Comment by aman566** [comment]
Hello sir,
Can I do more testing on your domains and report it to you?

Regards
Aman

**Comment by simonmichael** [comment]
Hi Aman.. no thank you. Best!
